name: Backup n8n

on:
  schedule:
    - cron: '25 14 * * *'  # Runs daily at 19:55 IST (14:25 UTC)

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Backup via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            bash ~/n8n-auto-deploy/backup.sh
