name: EC2 Scheduler

on:
  schedule:
    - cron: '25 3 * * *'   # Start EC2 at 09:00 IST (03:25 UTC)
    - cron: '30 14 * * *'  # Stop EC2 at 20:00 IST (14:30 UTC)

jobs:
  ec2-control:
    runs-on: ubuntu-latest
    steps:
      - name: Start or Stop EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.EC2_REGION }}
          INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        run: |
          if [[ "${{ github.event.schedule }}" == "25 3 * * *" ]]; then
            aws ec2 start-instances --instance-ids $INSTANCE_ID --region $AWS_REGION
          else
            aws ec2 stop-instances --instance-ids $INSTANCE_ID --region $AWS_REGION
          fi
