name: Start EC2 Instance

on:
  schedule:
    - cron: '0 3 * * 1-6'  # 9:00 AM IST, Monday to Saturday
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - name: Start EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.EC2_REGION }}
          INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        run: |
          aws ec2 start-instances --instance-ids $INSTANCE_ID --region $AWS_REGION
